### ISSUE TITLE
Update pkgver() function in PKGBUILD

### ISSUE THREAD

**Issue by Link-Satonaka** [orschiro/aclidswitch#2]
Add something like this to PKGBUILD so we can have useful version strings.
```bash
pkgver() {
  cd $_pkgname
  git describe --tags |sed 's/-/./g'
}
```
Or
```bash
pkgver() {
   cd $_pkgname
   echo "$(git rev-list --count HEAD).$(git describe --always )"
}

**Comment by orschiro** [comment]
Dear @Link-Satonaka,

Thanks for your request.

Can you please contact [vpzomtrrfrt](https://aur.archlinux.org/packages/aclidswitch-git/)?

I am no longer maintaining the PKGBUILD.

Thankfully,

~Robert
